#!/bin/sh

# Check if the script is running in interactive mode
if [ -t 1 ]; then
    # Prompt the user to decide whether to update the version
    read -p "Update version to $(versioningit)? [y/N] " response

    # Default response to 'N' if no input is provided
    response=${response:-N}

    # Check user response and update version if confirmed
    if [ "$response" = "Y" ] || [ "$response" = "y" ]; then
        # Run the version update script with the --commit flag
        "$(git rev-parse --git-dir)/../scripts/eyrie/update_version.sh" --commit
    else
        echo "Version update skipped."
    fi
else
    echo "Non-interactive mode detected; version update skipped."
fi
