#!/bin/sh
#
# `cd` to the project directory
#

# cd "$(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"
# echo "moved to: $(dirname "$(dirname "$(dirname "$(readlink -f "$0")")")")"


# # Prompt the user to decide whether to update the version
# read -p "Update version to $(versioningit)? [y/N] " response

# # Default response to 'N' if no input is provided
# response=${response:-N}

# # Check user response and update version if confirmed
# if [ "$response" = "Y" ] || [ "$response" = "y" ]; then
#     # Run the version update script with the --commit flag
#     "$(git rev-parse --git-dir)/../scripts/eyrie/update_version.sh" --commit
# else
#     echo "Version update skipped."
# fi


$(git rev-parse --git-dir)/../scripts/eyrie/update_version.sh --commit