#
# Vagrant/VirtualBox VM definitions
#
# (Use `vagrant status [box]` to see the list of defined boxes, and
# `vagrant (up|destroy|provision) [box]` to manage their lifecycles.)
#
# - Leading underscores exclude boxes from the list of VM definitions
# - The _base-box has all the essentials
# - The 'packages' list is a list of packages to `apt get` during provisioning
# - The 'states' list applies Salt states (.sls files) from config/salt/states/
# - The 'virtualbox' hash gets applied directly to the "virtualbox" provider
#

_base-box: &base
  box: "ubuntu/jammy64"
  memory: "2048"
  swap: "1G"
  project_root: /app

eyrie-dev: &eyriedev
  <<: *base
  private_ip: 192.168.33.30
  forwarded_ports:
    22: 2030
    80: 8030
    443: 8043
  # Include grains and minion configuration for the 'development' environment
  environment:
    - dev

eyrie-everything:
  <<: *eyriedev
  private_ip: 192.168.33.39
  packages:
    - task-gnome-desktop
  virtualbox:
    gui: true